openapi: 3.0.0
info:
  title: Billing Module API
  version: 1.0.0
  description: API endpoints for billing and subscription management
paths:
  /v1/billing/create-checkout-session:
    post:
      summary: Create Stripe checkout session
      description: Creates a Stripe checkout session for the authenticated user
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                priceId:
                  type: string
                  description: Stripe price ID
                successUrl:
                  type: string
                  format: uri
                  description: URL to redirect to after successful checkout
                cancelUrl:
                  type: string
                  format: uri
                  description: URL to redirect to if checkout is cancelled
              required:
                - priceId
      responses:
        '200':
          description: Checkout session created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  sessionId:
                    type: string
                  url:
                    type: string
                    format: uri
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  /v1/billing/create-customer-portal:
    post:
      summary: Create Stripe customer portal session
      description: Creates a Stripe customer portal session for the authenticated user
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                returnUrl:
                  type: string
                  format: uri
                  description: URL to return to after leaving the customer portal
      responses:
        '200':
          description: Customer portal session created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string
                    format: uri
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Customer not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  /v1/billing/subscription:
    get:
      summary: Get subscription
      description: Gets the subscription details for the authenticated user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Subscription details
          content:
            application/json:
              schema:
                type: object
                properties:
                  subscription:
                    type: object
                    nullable: true
                    properties:
                      id:
                        type: string
                      status:
                        type: string
                        enum: [active, canceled, incomplete, incomplete_expired, past_due, trialing, unpaid]
                      currentPeriodEnd:
                        type: string
                        format: date-time
                      cancelAtPeriodEnd:
                        type: boolean
                      priceId:
                        type: string
                      customerId:
                        type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  /api/webhooks/stripe:
    post:
      summary: Stripe webhook endpoint
      description: Endpoint for Stripe webhook events
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Webhook processed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  received:
                    type: boolean
        '400':
          description: Invalid webhook signature
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
  
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT